export const actionTypes = {
  REQUEST_LIST: "REQUEST_LIST",
  LOADING_DATA: "LOADING_DATA",
  FILTER_ITEMS: "FILTER_ITEMS",
  FILTER_ACTIVE: "FILTER_ACTIVE",
  CLEAR_SEARCH_VALUE: "CLEAR_SEARCH_VALUE",
  GET_LIST: "GET_LIST",
  SORT_TYPE: "SORT_TYPE",
};
